import Head from "next/head";
import { useRouter } from "next/router";
import dynamic from "next/dynamic";

export default function Home() {
  const router = useRouter();
  const QrReader = dynamic(() => import("react-qr-reader"), { ssr: false });

  const previewStyle = {
    height: 240,
    width: 320,
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>QRコードを読め</h1>
        <QrReader
          delay={1000}
          style={previewStyle}
          onScan={(data) => {
            if (data) {
              if (confirm(`ページを移動しますか？`)) {
                router.push(data);
              }
            }
          }}
          onError={(error) => {
            alert(error);
          }}
        ></QrReader>
      </main>
    </div>
  );
}
