import Head from "next/head";
import styles from "../styles/Home.module.css";
import dynamic from "next/dynamic";

export default function Home() {
  const QrReader = dynamic(() => import("react-qr-reader"), { ssr: false });

  const previewStyle = {
    height: 240,
    width: 320,
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>QRコードを読め</h1>
        <QrReader
          delay={1000}
          style={previewStyle}
          onScan={(data) => {
            if (data) {
              alert(data);
            }
          }}
          onError={(error) => {
            alert(error);
          }}
        ></QrReader>
      </main>
    </div>
  );
}
